version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: at_db
    ports:
      - '5439:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: at_db
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
